#!/usr/bin/env python3
"""
响应字段契约生成器（issue #64）

从 backend/openapi.json 的 components.schemas 抽取核心查询命令的响应字段契约，
生成 ir_cli/response_fields.py，供 `ir schema` 输出给 AI agent。

- 纯 stdlib 实现（CI 中无需安装任何依赖）；可从任意 cwd 运行（用 __file__ 定位仓库根）。
- SUMMARY_FIELDS 通过 ast 解析 ir_cli/utils.py 获得（避免 import 触发 httpx 依赖）。
- 紧凑编码：每命令一个单行字符串，字段格式 `[*]name:type[?]`，逗号连接；
  `*` 前缀 = 默认摘要字段，`?` 后缀 = 可空。
- NOTES_OVERRIDES 为人工标注层：键 "group.sub" 为命令级注释（输出 notes 键 "_"），
  键 "group.sub.field" 为字段级注释。
- 生成确定性：字段按 openapi properties 顺序输出，同一输入必得同一文件内容。

用法:
    python ir-cli/scripts/gen_response_fields.py           # 重新生成
    python ir-cli/scripts/gen_response_fields.py --check   # CI 防漂移校验（不一致 exit 1）
"""
import ast
import difflib
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
OPENAPI_PATH = REPO_ROOT / "backend" / "openapi.json"
UTILS_PATH = REPO_ROOT / "ir-cli" / "ir_cli" / "utils.py"
OUTPUT_PATH = REPO_ROOT / "ir-cli" / "ir_cli" / "response_fields.py"

REGEN_CMD = "python ir-cli/scripts/gen_response_fields.py"

# (命令组, 子命令, openapi schema 名, 响应形状 list/object, SUMMARY_FIELDS 资源键或 None)
COMMAND_SCHEMA_MAP = [
    ("position", "list", "PositionResponse", "list", "position"),
    ("portfolio", "create", "PortfolioResponse", "object", None),
    ("portfolio", "get", "PortfolioResponse", "object", None),
    ("portfolio", "update", "PortfolioResponse", "object", None),
    ("portfolio", "nav-history", "NavHistoryRecord", "list", None),
    ("portfolio", "performance", "PortfolioPerformance", "object", None),
    ("snapshot", "status", "SnapshotStatusResponse", "object", None),
    ("trade", "list", "TradeResponse", "list", "trade"),
    ("sub", "list", "SubscriptionResponse", "list", "subscription"),
    ("share-event", "list", "ShareChangeEventResponse", "list", None),
    ("asset-classification", "list", "AssetClassificationItem", "list", "asset_classification"),
    ("asset-classification", "get", "AssetClassificationDetail", "object", None),
]

# 人工标注层：openapi 无法表达的业务语义（键为 "group.sub" 或 "group.sub.field"）
NOTES_OVERRIDES = {
    "position.list.cash_amount": "仅CASH行有值，基金行恒为null（CHECK约束shares/cash_amount二选一），市值请用market_value",
    "position.list.shares": "净值型资产有值，CASH行为null",
    "portfolio.nav-history.total_value": "组合总市值（快照口径，为持仓行market_value之和）",
    "portfolio.nav-history": "单层列表按snapshot_date升序（#62已修复，勿再按data.data/date取值）",
    "portfolio.get.display_config": "持仓明细二级分组维度覆盖{'ASSET_STOCK': 'style'}；null=未配置=前端内置默认；仅存显式覆盖项，清空传null",
    "portfolio.update.display_config": "显式传null=清空配置；不传=不修改（exclude_unset 语义）",
    "portfolio.performance": "百分数口径（1.5表示1.5%）。快照不足时字段为null而非0，draft组合全为null",
    "portfolio.performance.twr": "时间加权收益率，消除资金进出影响；净值化记账下与累计净值增长率等价",
    "portfolio.performance.twr_chained": "逐期几何连乘的TWR，与twr应相等；不等说明净值序列异常",
    "portfolio.performance.mwr": "资金加权收益率(XIRR，年化)，考虑申赎时点；低于twr说明大部分资金买在高位。无现金流或无解时为null",
    "portfolio.performance.max_drawdown": "正值表示回撤幅度（如8.07表示最大跌8.07%），全程上涨时0",
    "portfolio.performance.annualized_volatility": "日收益率标准差按252交易日年化（收益率则按365日历日，口径不同）",
    "portfolio.performance.annualization_reliable": "false表示持有期<90天，年化指标属大幅外推（MWR可能达数百%），勿直接引用",
    "portfolio.performance.nav_series_consistent": "两种TWR算法一致性自检；false说明快照断层或净值异常，指标不可信",
    "asset-classification.list": "含停用值(is_active=false)，前端消费方自行过滤；维度级规则矩阵不在列表项内，用 get 单条或 API 顶层 dimension_rules",
    "asset-classification.list.applicable_asset_classes": "值级适用大类（asset_class 维度值恒为空 list），按大类色板序位排序",
    "asset-classification.list.sort_order": "asset_class 维度的序位即前端饼图/分区色板序位，变更即改色",
    "asset-classification.get.dimension_rules": "仅 asset_class 维度值有值：{dimension: rule}，rule ∈ required/optional，未出现的维度 = forbidden",
    "share-event.list.product_name": "读侧派生：仅 list 端点 join 产品表填充，产品缺失为null；get/单对象端点恒为null",
    "trade.list.cash_platform_code": "读侧派生（按配对CASH腿）：买入=扣款平台、卖出=到账平台；null=无配对现金腿（如待确认卖出，到账信息在确认时录入），CASH腿自身恒为null",
    "trade.list.cash_confirm_date": "读侧派生（按配对CASH腿）：买入=扣款日T、卖出=到账日A（缺省A=C）；null=无配对现金腿，CASH腿自身恒为null",
}

# openapi 类型 → 缩写
_TYPE_ABBREV = {
    "integer": "int",
    "number": "num",
    "boolean": "bool",
    "array": "list",
    "object": "obj",
}

FILE_HEADER = (
    '"""\n'
    "AUTO-GENERATED by scripts/gen_response_fields.py, do not edit.\n"
    f"Regenerate: {REGEN_CMD}\n"
    "\n"
    "响应字段契约（issue #64）：`ir schema` 在命中命令的条目中附加 output 键。\n"
    "fields 编码：`*`前缀=默认摘要字段（见 utils.SUMMARY_FIELDS），`?`后缀=可空。\n"
    '"""\n'
)


def _load_summary_fields() -> dict:
    """ast 解析 utils.py 中的 SUMMARY_FIELDS（不 import，避免 httpx 依赖）"""
    tree = ast.parse(UTILS_PATH.read_text(encoding="utf-8"))
    for node in tree.body:
        if isinstance(node, ast.Assign):
            for target in node.targets:
                if isinstance(target, ast.Name) and target.id == "SUMMARY_FIELDS":
                    return ast.literal_eval(node.value)
    raise RuntimeError(f"未在 {UTILS_PATH} 中找到 SUMMARY_FIELDS 赋值")


def _abbrev_type(prop: dict, context: str) -> str:
    """单个（已剥离 anyOf 的）property → 类型缩写；未识别输出 any 并 stderr 警告"""
    t = prop.get("type")
    if t == "string":
        fmt = prop.get("format")
        if fmt == "date":
            return "date"
        if fmt == "date-time":
            return "datetime"
        return "str"
    if t in _TYPE_ABBREV:
        return _TYPE_ABBREV[t]
    print(f"[warn] 未识别的类型 {prop!r}（{context}），记为 any", file=sys.stderr)
    return "any"


def _field_spec(name: str, prop: dict, required: set, summary: set, context: str) -> str:
    """单个字段 → `[*]name:type[?]`"""
    nullable = False
    effective = prop
    if "anyOf" in prop:
        members = [m for m in prop["anyOf"] if m.get("type") != "null"]
        nullable = len(members) != len(prop["anyOf"])
        effective = members[0] if members else {}
    # anyOf 未声明 null 时，按 required 列表补充判定（有默认值的字段响应中恒有值）
    if not nullable and name not in required and "default" not in prop:
        nullable = True
    type_abbrev = _abbrev_type(effective, f"{context}.{name}")
    prefix = "*" if name in summary else ""
    suffix = "?" if nullable else ""
    return f"{prefix}{name}:{type_abbrev}{suffix}"


def build_response_fields() -> dict:
    spec = json.loads(OPENAPI_PATH.read_text(encoding="utf-8"))
    schemas = spec["components"]["schemas"]
    summary_map = _load_summary_fields()

    result: dict = {}
    for group, sub, schema_name, shape, summary_key in COMMAND_SCHEMA_MAP:
        if schema_name not in schemas:
            print(f"[error] openapi.json 缺少 schema: {schema_name}", file=sys.stderr)
            sys.exit(1)
        schema = schemas[schema_name]
        required = set(schema.get("required", []))
        summary: set = set()
        if summary_key:
            summary = {f.strip() for f in summary_map[summary_key].split(",")}
        cmd_key = f"{group}.{sub}"
        props = schema.get("properties", {})
        fields = ",".join(
            _field_spec(name, prop, required, summary, cmd_key)
            for name, prop in props.items()
        )
        entry: dict = {"shape": shape, "fields": fields}
        notes: dict = {}
        if cmd_key in NOTES_OVERRIDES:
            notes["_"] = NOTES_OVERRIDES[cmd_key]
        for name in props:
            field_key = f"{cmd_key}.{name}"
            if field_key in NOTES_OVERRIDES:
                notes[name] = NOTES_OVERRIDES[field_key]
        if notes:
            entry["notes"] = notes
        result.setdefault(group, {})[sub] = entry
    return result


def render(data: dict) -> str:
    # 数据仅含 str/dict，json.dumps 输出即合法 Python 字面量；ensure_ascii=False 保持中文可读
    body = json.dumps(data, ensure_ascii=False, indent=4)
    return f"{FILE_HEADER}\nRESPONSE_FIELDS: dict = {body}\n"


def main() -> None:
    check_mode = "--check" in sys.argv[1:]
    content = render(build_response_fields())

    if check_mode:
        existing = OUTPUT_PATH.read_text(encoding="utf-8") if OUTPUT_PATH.exists() else ""
        if existing != content:
            diff = difflib.unified_diff(
                existing.splitlines(keepends=True),
                content.splitlines(keepends=True),
                fromfile=str(OUTPUT_PATH.relative_to(REPO_ROOT)),
                tofile="regenerated",
            )
            sys.stderr.writelines(diff)
            print(
                f"\n[error] 响应字段契约已漂移：请运行 `{REGEN_CMD}` 重新生成并提交",
                file=sys.stderr,
            )
            sys.exit(1)
        print("[ok] response_fields.py 与 openapi.json 一致", file=sys.stderr)
        sys.exit(0)

    OUTPUT_PATH.write_text(content, encoding="utf-8")
    print(f"[ok] 已生成 {OUTPUT_PATH.relative_to(REPO_ROOT)}", file=sys.stderr)


if __name__ == "__main__":
    main()
