"""
AUTO-GENERATED by scripts/gen_response_fields.py, do not edit.
Regenerate: python ir-cli/scripts/gen_response_fields.py

响应字段契约（issue #64）：`ir schema` 在命中命令的条目中附加 output 键。
fields 编码：`*`前缀=默认摘要字段（见 utils.SUMMARY_FIELDS），`?`后缀=可空。
"""

RESPONSE_FIELDS: dict = {
    "position": {
        "list": {
            "shape": "list",
            "fields": "*portfolio_code:str,*product_code:str,*market:str?,*platform_code:str?,*shares:num?,frozen_shares:num?,cost_price:num?,*unit_price:num?,*market_value:num?,*amount:num?,frozen_amount:num?,*snapshot_date:date,*id:int,created_at:datetime?",
            "notes": {
                "shares": "净值型资产有值，CASH行为null",
                "amount": "仅CASH行有值，基金行恒为null（CHECK约束shares/amount二选一），市值请用market_value"
            }
        }
    },
    "portfolio": {
        "nav-history": {
            "shape": "list",
            "fields": "snapshot_date:date,unit_price:num?,total_value:num?,total_shares:num?",
            "notes": {
                "_": "单层列表按snapshot_date升序（#62已修复，勿再按data.data/date取值）",
                "total_value": "组合总市值（快照口径，为持仓行market_value之和）"
            }
        }
    },
    "snapshot": {
        "status": {
            "shape": "object",
            "fields": "portfolio_code:str,latest_snapshot_date:date?,total_snapshots:int,first_snapshot_date:date?,missing_dates:list"
        }
    },
    "trade": {
        "list": {
            "shape": "list",
            "fields": "*portfolio_code:str,*product_code:str,*market:str?,*platform_code:str?,*trade_type:str,transfer_group:str?,*shares:num?,*amount:num?,*price:num?,fee:num,actual_amount:num?,*trade_date:date,*confirm_date:date?,*status:str,notes:str?,*id:int,created_at:datetime?,updated_at:datetime?"
        }
    },
    "sub": {
        "list": {
            "shape": "list",
            "fields": "*portfolio_code:str,*investor_code:str,*platform_code:str,*sub_type:str,*amount:num?,*shares:num?,*unit_price:num?,*apply_date:date,*confirm_date:date?,*status:str,notes:str?,*id:int,created_at:datetime?,updated_at:datetime?"
        }
    }
}
