"""
AUTO-GENERATED by scripts/gen_response_fields.py, do not edit.
Regenerate: python ir-cli/scripts/gen_response_fields.py

响应字段契约（issue #64）：`ir schema` 在命中命令的条目中附加 output 键。
fields 编码：`*`前缀=默认摘要字段（见 utils.SUMMARY_FIELDS），`?`后缀=可空。
"""

RESPONSE_FIELDS: dict = {
    "position": {
        "list": {
            "shape": "list",
            "fields": "*portfolio_code:str,*product_code:str,*market:str?,*platform_code:str?,*shares:num?,frozen_shares:num?,cost_price:num?,*unit_price:num?,*market_value:num?,*cash_amount:num?,frozen_amount:num?,*snapshot_date:date,*id:int,created_at:datetime?,product_name:str?,profit_loss:num?,profit_loss_percent:num?,asset_class_code:str?,asset_class_name:str?,region_code:str?,region_name:str?,style_code:str?,style_name:str?,size_code:str?,size_name:str?,segment_code:str?,segment_name:str?,daily_profit:num?,is_qdii:bool?,nav_lag_days:int?,platform_name:str?",
            "notes": {
                "shares": "净值型资产有值，CASH行为null",
                "cash_amount": "仅CASH行有值，基金行恒为null（CHECK约束shares/cash_amount二选一），市值请用market_value"
            }
        }
    },
    "portfolio": {
        "create": {
            "shape": "object",
            "fields": "code:str,name:str,description:str?,status:str,started_at:datetime?,closed_at:datetime?,created_at:datetime?,updated_at:datetime?,display_config:obj?,auto_snapshot_enabled:bool,total_value:num?,total_profit:num?"
        },
        "get": {
            "shape": "object",
            "fields": "code:str,name:str,description:str?,status:str,started_at:datetime?,closed_at:datetime?,created_at:datetime?,updated_at:datetime?,display_config:obj?,auto_snapshot_enabled:bool,total_value:num?,total_profit:num?",
            "notes": {
                "display_config": "持仓明细二级分组维度覆盖{'ASSET_STOCK': 'style'}；null=未配置=前端内置默认；仅存显式覆盖项，清空传null"
            }
        },
        "update": {
            "shape": "object",
            "fields": "code:str,name:str,description:str?,status:str,started_at:datetime?,closed_at:datetime?,created_at:datetime?,updated_at:datetime?,display_config:obj?,auto_snapshot_enabled:bool,total_value:num?,total_profit:num?",
            "notes": {
                "display_config": "显式传null=清空配置；不传=不修改（exclude_unset 语义）"
            }
        },
        "nav-history": {
            "shape": "list",
            "fields": "snapshot_date:date,unit_price:num?,total_value:num?,total_shares:num?",
            "notes": {
                "_": "单层列表按snapshot_date升序（#62已修复，勿再按data.data/date取值）",
                "total_value": "组合总市值（快照口径，为持仓行market_value之和）"
            }
        },
        "performance": {
            "shape": "object",
            "fields": "portfolio_code:str,twr:num?,twr_chained:num?,annualized_twr:num?,mwr:num?,initial_nav:num?,current_nav:num?,holding_days:int?,return_1m:num?,return_3m:num?,return_6m:num?,return_ytd:num?,return_1y:num?,return_3y:num?,max_drawdown:num?,max_drawdown_peak_date:str?,max_drawdown_trough_date:str?,annualized_volatility:num?,cash_flow_count:int,nav_series_consistent:bool?,annualization_reliable:bool",
            "notes": {
                "_": "百分数口径（1.5表示1.5%）。快照不足时字段为null而非0，draft组合全为null",
                "twr": "时间加权收益率，消除资金进出影响；净值化记账下与累计净值增长率等价",
                "twr_chained": "逐期几何连乘的TWR，与twr应相等；不等说明净值序列异常",
                "mwr": "资金加权收益率(XIRR，年化)，考虑申赎时点；低于twr说明大部分资金买在高位。无现金流或无解时为null",
                "max_drawdown": "正值表示回撤幅度（如8.07表示最大跌8.07%），全程上涨时0",
                "annualized_volatility": "日收益率标准差按252交易日年化（收益率则按365日历日，口径不同）",
                "nav_series_consistent": "两种TWR算法一致性自检；false说明快照断层或净值异常，指标不可信",
                "annualization_reliable": "false表示持有期<90天，年化指标属大幅外推（MWR可能达数百%），勿直接引用"
            }
        }
    },
    "snapshot": {
        "status": {
            "shape": "object",
            "fields": "portfolio_code:str,latest_snapshot_date:date?,total_snapshots:int,first_snapshot_date:date?,missing_dates:list,negative_cash_platforms:list,auto_snapshot_enabled:bool"
        }
    },
    "trade": {
        "list": {
            "shape": "list",
            "fields": "*portfolio_code:str,*product_code:str,*market:str?,*platform_code:str?,*trade_type:str,transfer_group:str?,*shares:num?,*amount:num?,*price:num?,fee:num,actual_amount:num?,*trade_date:date,*confirm_date:date?,*status:str,notes:str?,*id:int,created_at:datetime?,updated_at:datetime?,product_name:str?,*cash_platform_code:str?,*cash_confirm_date:date?"
        }
    },
    "sub": {
        "list": {
            "shape": "list",
            "fields": "*portfolio_code:str,*investor_code:str,*platform_code:str,*sub_type:str,*amount:num?,*shares:num?,*unit_price:num?,*apply_date:date,*confirm_date:date?,*status:str,notes:str?,*id:int,created_at:datetime?,updated_at:datetime?"
        }
    },
    "share-event": {
        "list": {
            "shape": "list",
            "fields": "portfolio_code:str,event_type:str,ex_date:date,entitlement_date:date,platform_code:str?,parent_event_id:int?,product_code:str?,market:str?,event_source:str,entitlement_shares:num?,shares_before:num?,shares_change:num?,shares_after:num?,cash_change:num?,cash_product_code:str?,div_cash:num?,reinvest_nav:num?,ratio:num?,status:str,tushare_event_id:str?,notes:str?,id:int,created_at:datetime?,updated_at:datetime?,product_name:str?",
            "notes": {
                "product_name": "读侧派生：仅 list 端点 join 产品表填充，产品缺失为null；get/单对象端点恒为null"
            }
        }
    },
    "asset-classification": {
        "list": {
            "shape": "list",
            "fields": "*code:str,*dimension:str,*name:str,*sort_order:int,description:str?,*is_active:bool,*applicable_asset_classes:list",
            "notes": {
                "_": "含停用值(is_active=false)，前端消费方自行过滤；维度级规则矩阵不在列表项内，用 get 单条或 API 顶层 dimension_rules",
                "sort_order": "asset_class 维度的序位即前端饼图/分区色板序位，变更即改色",
                "applicable_asset_classes": "值级适用大类（asset_class 维度值恒为空 list），按大类色板序位排序"
            }
        },
        "get": {
            "shape": "object",
            "fields": "code:str,dimension:str,name:str,sort_order:int,description:str?,is_active:bool,applicable_asset_classes:list,dimension_rules:obj",
            "notes": {
                "dimension_rules": "仅 asset_class 维度值有值：{dimension: rule}，rule ∈ required/optional，未出现的维度 = forbidden"
            }
        }
    }
}
